services:
  manager:
    image: sleep-server
    build: .
    command: ./hello_world manager
    stdin_open: true
    tty: true
    profiles: [manager]
  host:
    image: sleep-server
    command: ./hello_world srv
    stdin_open: true
    tty: true
    profiles: [host]
    deploy:
      mode: replicated
      replicas: 1
