services:
  manager:
    image: sleep-server
    build: .
    command: ./sleep_server manager
    stdin_open: true
    tty: true
    profiles: [manager]
  host:
    image: sleep-server
    command: ./sleep_server srv
    stdin_open: false
    tty: false
    profiles: [host]
    deploy:
      mode: replicated
      replicas: 2
